
use_frameworks!

platform :ios, '9.0'

target 'KYPerformanceMonitor_Example' do
  #pod 'KYPerformanceMonitor', '~>0.1.0'
  pod 'KYPerformanceMonitor', path: '../'
  
  target 'KYPerformanceMonitor_Tests' do
    inherit! :search_paths

    
  end
end
